/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TimelockInterface extends ethers.utils.Interface {
  functions: {
    "addGrants(address[],uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "claim()": FunctionFragment;
    "decimals()": FunctionFragment;
    "getTimeRecover()": FunctionFragment;
    "getTimeUnlock()": FunctionFragment;
    "getToken()": FunctionFragment;
    "grantedAmount(address)": FunctionFragment;
    "name()": FunctionFragment;
    "recover()": FunctionFragment;
    "symbol()": FunctionFragment;
    "timeReceiveGrant()": FunctionFragment;
    "timeRecoverGrant()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addGrants",
    values: [string[], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTimeRecover",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUnlock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "grantedAmount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "recover", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timeReceiveGrant",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeRecoverGrant",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addGrants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTimeRecover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUnlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recover", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timeReceiveGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeRecoverGrant",
    data: BytesLike
  ): Result;

  events: {
    "Claimed(address,uint256)": EventFragment;
    "GrantsAdded(address,address[])": EventFragment;
    "Recovered(address,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantsAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Recovered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export class Timelock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TimelockInterface;

  functions: {
    addGrants(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addGrants(address[],uint256)"(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    claim(overrides?: Overrides): Promise<ContractTransaction>;

    "claim()"(overrides?: Overrides): Promise<ContractTransaction>;

    decimals(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "decimals()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    getTimeRecover(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getTimeRecover()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    getTimeUnlock(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getTimeUnlock()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    getToken(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "getToken()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    grantedAmount(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "grantedAmount(address)"(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    name(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "name()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    recover(overrides?: Overrides): Promise<ContractTransaction>;

    "recover()"(overrides?: Overrides): Promise<ContractTransaction>;

    symbol(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "symbol()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    timeReceiveGrant(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "timeReceiveGrant()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    timeRecoverGrant(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "timeRecoverGrant()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  addGrants(
    newRecipients: string[],
    grantSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addGrants(address[],uint256)"(
    newRecipients: string[],
    grantSize: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claim(overrides?: Overrides): Promise<ContractTransaction>;

  "claim()"(overrides?: Overrides): Promise<ContractTransaction>;

  decimals(overrides?: CallOverrides): Promise<number>;

  "decimals()"(overrides?: CallOverrides): Promise<number>;

  getTimeRecover(overrides?: CallOverrides): Promise<BigNumber>;

  "getTimeRecover()"(overrides?: CallOverrides): Promise<BigNumber>;

  getTimeUnlock(overrides?: CallOverrides): Promise<BigNumber>;

  "getTimeUnlock()"(overrides?: CallOverrides): Promise<BigNumber>;

  getToken(overrides?: CallOverrides): Promise<string>;

  "getToken()"(overrides?: CallOverrides): Promise<string>;

  grantedAmount(
    recipient: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "grantedAmount(address)"(
    recipient: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  recover(overrides?: Overrides): Promise<ContractTransaction>;

  "recover()"(overrides?: Overrides): Promise<ContractTransaction>;

  symbol(overrides?: CallOverrides): Promise<string>;

  "symbol()"(overrides?: CallOverrides): Promise<string>;

  timeReceiveGrant(overrides?: CallOverrides): Promise<BigNumber>;

  "timeReceiveGrant()"(overrides?: CallOverrides): Promise<BigNumber>;

  timeRecoverGrant(overrides?: CallOverrides): Promise<BigNumber>;

  "timeRecoverGrant()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addGrants(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addGrants(address[],uint256)"(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(overrides?: CallOverrides): Promise<void>;

    "claim()"(overrides?: CallOverrides): Promise<void>;

    decimals(overrides?: CallOverrides): Promise<number>;

    "decimals()"(overrides?: CallOverrides): Promise<number>;

    getTimeRecover(overrides?: CallOverrides): Promise<BigNumber>;

    "getTimeRecover()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTimeUnlock(overrides?: CallOverrides): Promise<BigNumber>;

    "getTimeUnlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    getToken(overrides?: CallOverrides): Promise<string>;

    "getToken()"(overrides?: CallOverrides): Promise<string>;

    grantedAmount(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "grantedAmount(address)"(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    recover(overrides?: CallOverrides): Promise<void>;

    "recover()"(overrides?: CallOverrides): Promise<void>;

    symbol(overrides?: CallOverrides): Promise<string>;

    "symbol()"(overrides?: CallOverrides): Promise<string>;

    timeReceiveGrant(overrides?: CallOverrides): Promise<BigNumber>;

    "timeReceiveGrant()"(overrides?: CallOverrides): Promise<BigNumber>;

    timeRecoverGrant(overrides?: CallOverrides): Promise<BigNumber>;

    "timeRecoverGrant()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    Claimed(actor: null, amount: null): EventFilter;

    GrantsAdded(actor: null, newRecipients: null): EventFilter;

    Recovered(recipient: null, amount: null): EventFilter;

    Transfer(from: string | null, to: string | null, tokens: null): EventFilter;
  };

  estimateGas: {
    addGrants(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addGrants(address[],uint256)"(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(overrides?: Overrides): Promise<BigNumber>;

    "claim()"(overrides?: Overrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTimeRecover(overrides?: CallOverrides): Promise<BigNumber>;

    "getTimeRecover()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTimeUnlock(overrides?: CallOverrides): Promise<BigNumber>;

    "getTimeUnlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    getToken(overrides?: CallOverrides): Promise<BigNumber>;

    "getToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    grantedAmount(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "grantedAmount(address)"(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    recover(overrides?: Overrides): Promise<BigNumber>;

    "recover()"(overrides?: Overrides): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: CallOverrides): Promise<BigNumber>;

    timeReceiveGrant(overrides?: CallOverrides): Promise<BigNumber>;

    "timeReceiveGrant()"(overrides?: CallOverrides): Promise<BigNumber>;

    timeRecoverGrant(overrides?: CallOverrides): Promise<BigNumber>;

    "timeRecoverGrant()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addGrants(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addGrants(address[],uint256)"(
      newRecipients: string[],
      grantSize: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(overrides?: Overrides): Promise<PopulatedTransaction>;

    "claim()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "decimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTimeRecover(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getTimeRecover()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTimeUnlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getTimeUnlock()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grantedAmount(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "grantedAmount(address)"(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recover(overrides?: Overrides): Promise<PopulatedTransaction>;

    "recover()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "symbol()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timeReceiveGrant(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "timeReceiveGrant()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    timeRecoverGrant(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "timeRecoverGrant()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
